Task 8
ozoncp/ocp-snippet-api pull request #13
Opened 2021-06-18 12:31 UTC by oLESHIYka

- Реализованы ручки MultiCreateEntity и UpdateEntity.
 - Добавлен трейсинг для ручек.
 - Добавлен Producer сообщающий в кафку об успешном выполнении (на самом деле не всегда успешном, надо поправить...) CUD-событий.
 - Добавлены метрики для CRUD-ручек.

2021-06-18 14:48 UTC, LiFeAiR requested changes

2021-06-18 14:48 UTC, LiFeAiR commented on api/ocp-snippet-api/ocp-snippet-api.proto
> +			post: "/snippets/multi_create/v1"
по моему тут надо добавлять
`"body": "*"`
во всех post запросах

2021-06-18 14:48 UTC, LiFeAiR commented on api/ocp-snippet-api/ocp-snippet-api.proto
> +	uint64 user_id     = 3;
опять что. то с форматированием

2021-06-18 14:48 UTC, LiFeAiR commented on internal/api/api.go
> +	for idx, snippet := range req.Snippets { // Корявенько выглядит...
ну да у тебя же есть функция `snippetConvert`, используй ее
ну или создай что то подобное

2021-06-18 14:48 UTC, LiFeAiR commented on internal/repo/repo.go
> +
лишний перенос

2021-06-18 14:48 UTC, LiFeAiR commented on internal/repo/repo.go
> +	"database/sql"
это не тут

2021-06-18 14:48 UTC, LiFeAiR commented on internal/repo/repo.go
> +func NewRepoDB(db *sql.DB) repoDB {
всегда юзаю ссылку на объект `*repoDB`
а при создании `&repoDb{}`
ну и в функциях `func (repo *repoDB) addSnippetsBatch`

2021-06-20 19:12 UTC, rusdevops approved these changes

2021-06-21 14:38 UTC, merged